export interface AreaConfig {
  slug: string;
  name: string;
  query: string;  // what to pass to the search API
  radius_km: number;
  description: string;
  county: string;  // parent county slug (e.g. "dublin", "cork")
  // Area-page locality filter (passed to /search and /trends). A result is kept only
  // if its address names one of `match` OR its eircode routing key is in `routing_keys`.
  // Excludes properties mis-geocoded onto a same-named street in another town.
  match: string[];          // curated locality terms found in genuine local addresses
  routing_keys?: string[];  // eircode routing keys covering the area (empirically derived)
  info?: string;   // one-paragraph factual overview (setting, population, landmarks)
  image?: string;  // optional hero photo path under /images (public/)
  imageAlt?: string; // alt text for the hero photo
  image2?: string;  // optional second photo, shown lower in the page body
  imageAlt2?: string; // alt text for the second photo
}

export const AREAS: AreaConfig[] = [
  { slug: "rathmines", match: ["Rathmines"], routing_keys: ["D06"], name: "Rathmines", query: "Rathmines, Dublin", radius_km: 1.5, description: "a popular inner-city suburb on Dublin's southside", county: "dublin",
    info: "Rathmines is an inner southside suburb of Dublin, in postal district Dublin 6, bounded to the north by the Grand Canal, long known for its density of subdivided Georgian and Victorian houses. Landmarks include Rathmines Town Hall, whose clock tower is nicknamed the 'Four Faced Liar', the domed Church of Mary Immaculate Refuge of Sinners, the Carnegie-funded Rathmines Library, and the Stella Cinema." },
  { slug: "ranelagh", match: ["Ranelagh"], routing_keys: ["D06"], name: "Ranelagh", query: "Ranelagh, Dublin", radius_km: 1, description: "one of Dublin's most sought-after residential villages", county: "dublin",
    info: "Ranelagh is an affluent residential area and urban village on Dublin's southside, in postal district Dublin 6, originally known as Cullenswood before its 19th-century development. Landmarks include Ranelagh Gardens, an 18th-century pleasure ground where Richard Crosbie made Ireland's first hot air balloon flight in 1785, the Ranelagh Arts Centre, and Scoil Bhríde, the first gaelscoil (Irish-language school) in Ireland, founded in 1917. Two Luas tram stops serve the village." },
  { slug: "blackrock", match: ["Blackrock"], routing_keys: ["A94"], name: "Blackrock", query: "Blackrock, Dublin", radius_km: 1.5, description: "a coastal suburb south of Dublin city centre", county: "dublin",
    info: "Blackrock is an affluent coastal suburb in Dún Laoghaire-Rathdown, on Dublin Bay about 3km northwest of Dún Laoghaire. Its electoral division recorded a population of 31,152 in Census 2022. The area grew after Blackrock railway station opened in 1834, the oldest in Ireland, with DART services now linking it to the city centre in about 15 minutes. Landmarks include Blackrock Park, site of an early 19th-century Martello tower, and Blackrock Market." },
  { slug: "dun-laoghaire", match: ["Dun Laoghaire", "Glasthule", "Sandycove", "Monkstown"], routing_keys: ["A96", "A94"], name: "Dún Laoghaire", query: "Dún Laoghaire, Dublin", radius_km: 2, description: "a coastal town and harbour south of Dublin", county: "dublin",
    info: "Dún Laoghaire is a coastal town on Dublin's southside, its name meaning 'fort of Laoghaire' after a 5th-century High King. Census 2022 recorded 31,239 residents, up from 26,525 in 2016. The town is built around a harbour with two granite piers dating from 1817 to 1859, including the popular East Pier, and hosts an 820-berth marina, the largest in Ireland, plus the National Maritime Museum.",
    image: "/images/dun-laoghaire-harbour.jpg", imageAlt: "A dinghy sailing in Dún Laoghaire harbour, with the town and the spire of the Mariners' Church (National Maritime Museum) behind" },
  { slug: "clontarf", match: ["Clontarf"], routing_keys: ["D03"], name: "Clontarf", query: "Clontarf, Dublin", radius_km: 1.5, description: "a seaside suburb on Dublin's northside", county: "dublin",
    info: "Clontarf is an affluent coastal suburb on Dublin's northside, in postal district Dublin 3, fronting Dublin Bay with a promenade running 4.5km to Dollymount. It was the site of the Battle of Clontarf in 1014, in which Brian Boru's forces defeated a Viking and Leinster alliance. Landmarks include Clontarf Castle, St Anne's Park, and North Bull Island, home to two golf courses, a nature reserve, and a replica Easter Island moai.",
    image: "/images/clontarf-harbour.jpg", imageAlt: "Sailboats moored on Dublin Bay off Clontarf, with Howth Head in the distance" },
  { slug: "howth", match: ["Howth", "Sutton", "Baldoyle"], routing_keys: ["D13"], name: "Howth", query: "Howth, Dublin", radius_km: 2, description: "a picturesque fishing village and peninsula north of Dublin", county: "dublin",
    info: "Howth is a peninsular fishing village and outer suburb of Dublin, roughly 14km northeast of the city centre on Howth Head, which forms the northern edge of Dublin Bay. Census 2022 recorded an urban population of 8,399. It remains a tier-2 fishing port with an active harbour and marina. Landmarks include Howth Castle, the adjacent Aideen's Grave dolmen, the Bailey Lighthouse, a 6km cliff path loop, and the offshore island of Ireland's Eye.",
    image: "/images/howth-cliff-path-baily.jpg", imageAlt: "View south along the Howth Head cliff path over Dublin Bay, with the Baily Lighthouse on the headland and the Dublin mountains faint on the horizon" },
  { slug: "malahide", match: ["Malahide"], routing_keys: ["K36"], name: "Malahide", query: "Malahide, Dublin", radius_km: 2, description: "a coastal village north of Dublin known for its castle and marina", county: "dublin",
    info: "Malahide is a coastal settlement roughly 14km north of Dublin city, with a village centre bordered by suburban housing and an estuary where the Broadmeadow River meets the sea. Census 2022 recorded a population of 18,608. The area is dominated by Malahide Castle, dating from the 12th century, set within a demesne that includes an international cricket ground. A marina and sandy beach line the shorefront." },
  { slug: "stillorgan", match: ["Stillorgan"], routing_keys: ["A94"], name: "Stillorgan", query: "Stillorgan, Dublin", radius_km: 1.5, description: "a suburban area in south County Dublin", county: "dublin",
    info: "Stillorgan is a suburban area in Dun Laoghaire-Rathdown, south Co. Dublin, with a population of 18,212 recorded in the 2022 census. Once a village in its own right, it retains an old village centre alongside later housing estates. Notable features include the 18th-century Stillorgan Obelisk, designed by Edward Lovett Pearce, and Stillorgan Shopping Centre, which opened in 1966 as Ireland's first shopping centre.",
    image: "/images/stillorgan-shopping-centre.jpg", imageAlt: "Stillorgan Shopping Centre, with its landmark orange sign, seen across the junction at the village centre, with a Permanent TSB branch and shoppers crossing to the right",
    image2: "/images/stillorgan-new-apartments.jpg", imageAlt2: "Recently completed apartment blocks at a road junction in Stillorgan, part of the higher-density housing built around the older suburb in recent years" },
  { slug: "sandymount", match: ["Sandymount"], routing_keys: ["D04"], name: "Sandymount", query: "Sandymount, Dublin", radius_km: 1, description: "a coastal village close to Dublin city centre", county: "dublin",
    info: "Sandymount is a coastal suburb in the Dublin 4 district, three to four kilometres south-east of Dublin city centre. The area is fronted by Sandymount Strand, an extensive beach forming part of the southern shore of Dublin Bay, and includes a Martello tower built as part of early 19th-century coastal defences against a feared Napoleonic invasion. Sandymount Green, a triangular park bordered by shops and cafes, sits at the centre of the village.",
    image: "/images/sandymount-strand-sunset.jpg", imageAlt: "Sunset over Sandymount Strand at low tide, with the Poolbeg chimneys and Dublin Port cranes on the horizon reflected in the wet sand" },
  { slug: "portobello", match: ["Portobello"], routing_keys: ["D08"], name: "Portobello", query: "Portobello, Dublin", radius_km: 1, description: "a vibrant canalside neighbourhood in Dublin 8", county: "dublin",
    info: "Portobello is a canalside neighbourhood in Dublin's southern city centre, bounded to the south by the Grand Canal. It expanded as a suburb through the 18th and 19th centuries and, from the late 19th century, became known as Dublin's \"Little Jerusalem\" after Ashkenazi Jewish families settled there; the Irish Jewish Museum on Walworth Road records this history. Other landmarks include Portobello Barracks, built 1810-1815, and La Touche Bridge over the canal." },
  { slug: "galway-city", match: ["Galway"], routing_keys: ["H91"], name: "Galway City", query: "Galway City", radius_km: 3, description: "the cultural capital of the west of Ireland", county: "galway",
    info: "Galway City lies on Ireland's west coast where the River Corrib flows between Lough Corrib and Galway Bay, and recorded a population of 85,910 in the 2022 census, the state's fourth most populous urban area. The medieval core includes the Spanish Arch, built in 1519-20, and Lynch's Castle, a 16th-century townhouse on Shop Street. St Nicholas' Collegiate Church, founded in 1320, and the Claddagh, a historic fishing quarter, are also notable." },
  { slug: "salthill", match: ["Salthill"], routing_keys: ["H91"], name: "Salthill", query: "Salthill, Galway", radius_km: 1.5, description: "a seaside suburb of Galway city with a popular promenade", county: "galway",
    info: "Salthill is a seaside suburb to the south-west of Galway city centre, on the shore of Galway Bay; the 2016 census recorded a population of 3,650. Developed as a Victorian bathing resort, it retains a two-kilometre promenade, known locally as \"the Prom\", opened in 1856. Other landmarks include the Blackrock diving tower, built in 1953 and used for Christmas Day swimming, and Pearse Stadium, a Galway GAA venue." },
  { slug: "oranmore", match: ["Oranmore"], routing_keys: ["H91"], name: "Oranmore", query: "Oranmore, Galway", radius_km: 2, description: "a growing commuter town east of Galway city", county: "galway",
    info: "Oranmore is a town on an inlet of Galway Bay, roughly 9km east of Galway city, County Galway. The 2022 census recorded a population of 5,819, reflecting steady growth as a commuter base for Galway city. Landmarks include the 15th-century Oranmore Castle, medieval church ruins with a gravestone dated 1661, and St Mary's Church, built in 1803 and now the town library." },
  { slug: "athenry", match: ["Athenry"], routing_keys: ["H65"], name: "Athenry", query: "Athenry, Galway", radius_km: 2, description: "a historic walled town in County Galway", county: "galway",
    info: "Athenry is a medieval town in County Galway, some 25km east of Galway city, notable for retaining around 70% of its original town wall circuit. The 2022 census recorded a population of 4,603. Landmarks include Athenry Castle, built before 1240; the 13th-century Dominican Priory; and the late 15th-century Market Cross, the only medieval cross still standing in its original position in Ireland." },
  { slug: "tuam", match: ["Tuam"], routing_keys: ["H54"], name: "Tuam", query: "Tuam, Galway", radius_km: 2, description: "a market town in north County Galway", county: "galway",
    info: "Tuam is a market town in north County Galway, about 35km north of Galway city, and an ecclesiastical centre tracing its origins to a monastic settlement founded by St Jarlath. The 2022 census recorded a population of 9,647. Landmarks include the Cathedral of the Assumption (1827-1837), St Mary's Cathedral, which houses the High Cross of Tuam dated to 1152, the ruins of Temple Jarlath, and the Mill Museum's restored waterwheel." },
  { slug: "connemara", match: ["Clifden", "Connemara", "Roundstone", "Ballyconneely", "Letterfrack"], routing_keys: ["H71"], name: "Connemara", query: "Clifden, Galway", radius_km: 5, description: "a scenic rural region on Galway's western coast", county: "galway",
    info: "Connemara is a rugged coastal region in west County Galway, characterised by mountains including the Twelve Bens, blanket bog, small lakes and an indented Atlantic shoreline. Its principal town, Clifden, recorded a population of 1,259 at the 2022 census. Notable sites include Connemara National Park, Kylemore Abbey, the ruined Clifden Castle, and the Sky Road, an 11km scenic coastal route." },
  { slug: "cork-city", match: ["Cork"], routing_keys: ["T12", "T23"], name: "Cork City", query: "Cork City", radius_km: 3, description: "Ireland's second city on the River Lee", county: "cork",
    info: "Cork is Ireland's second-largest city, built on an island between two channels of the River Lee before they converge into Cork Harbour. The 2022 census recorded a population of 224,004 within the city boundary. Landmarks include St Fin Barre's Cathedral, the English Market, trading since 1610, St Anne's Church in Shandon, and University College Cork, whose grounds border the river." },
  { slug: "douglas", match: ["Douglas"], routing_keys: ["T12"], name: "Douglas", query: "Douglas, Cork", radius_km: 1.5, description: "an upscale suburb on Cork city's southside", county: "cork",
    info: "Douglas is a suburb with a village core on the southside of Cork city, formally incorporated into the Cork City Council area in May 2019. At the 2016 census, the Douglas electoral division recorded a population of approximately 26,883. Landmarks include Douglas Village Shopping Centre, opened in the mid-1970s and described as Ireland's second shopping centre, St Luke's Church (1875), and Ballybrack Woods." },
  { slug: "ballincollig", match: ["Ballincollig"], routing_keys: ["P31"], name: "Ballincollig", query: "Ballincollig, Cork", radius_km: 2, description: "a large commuter town west of Cork city", county: "cork",
    info: "Ballincollig is a town on the River Lee to the west of Cork city, brought within the Cork City Council boundary in 2019. At the 2016 census, the Ballincollig electoral division recorded a population of 18,621, then the largest town in County Cork. Landmarks include Ballincollig Regional Park, a 135-acre site incorporating the former Royal Gunpowder Mills, established in 1794, and the ruined Ballincollig Castle." },
  { slug: "carrigaline", match: ["Carrigaline"], routing_keys: ["P43"], name: "Carrigaline", query: "Carrigaline, Cork", radius_km: 2, description: "a growing town south of Cork city", county: "cork",
    info: "Carrigaline is a town on the River Owenabue in County Cork, roughly 12km south of Cork city, functioning as one of the county's largest commuter towns. Census 2022 recorded a population of 18,239, up 15.7% from 2016. Landmarks include St Mary's Church (1824), Our Lady and John Church (1957), and the former Carrigaline Pottery on Main Street. The town also serves as a gateway to West Cork." },
  { slug: "cobh", match: ["Cobh"], routing_keys: ["P24"], name: "Cobh", query: "Cobh, Cork", radius_km: 2, description: "a historic port town on Cork harbour", county: "cork",
    info: "Cobh is a seaport town on Great Island in Cork Harbour, County Cork, known for its Victorian terraces, including the colourful row nicknamed the 'deck of cards', beneath St Colman's Cathedral. Census 2022 recorded a population of 14,148. Formerly Queenstown, it was the Titanic's final port of call in 1912 and a major 19th-century emigration point. Sites include the Cobh Heritage Centre, Titanic Experience Museum, and nearby Spike Island." },
  { slug: "midleton", match: ["Midleton"], routing_keys: ["P25"], name: "Midleton", query: "Midleton, Cork", radius_km: 2, description: "a market town and distillery gateway in East Cork", county: "cork",
    info: "Midleton is a market town in East Cork, about 16km east of Cork city, serving as the commercial hub of the area. Census 2022 recorded a population of 13,906, roughly double its 1996 figure. It is home to the Old Midleton Distillery, founded in 1825 and now housing the Jameson Experience visitor centre, which contains the world's largest pot still and Ireland's largest working waterwheel. Midleton Library dates to 1789." },
  { slug: "kinsale", match: ["Kinsale"], routing_keys: ["P17"], name: "Kinsale", query: "Kinsale, Cork", radius_km: 2, description: "a coastal gourmet destination and sailing hub in County Cork", county: "cork",
    info: "Kinsale is a harbour town on the River Bandon estuary in County Cork, around 25km south of Cork city, noted for its narrow streets and colourfully painted shopfronts. Census 2022 recorded a population of 5,991. Historic sites include Charles Fort (1677), James Fort (1607), and Desmond Castle, a 16th-century tower house. The town is known for its restaurant scene and active sailing community centred on Kinsale Yacht Club.",
    image: "/images/kinsale-charles-fort.jpg", imageAlt: "The classical entrance gateway and wooden footbridge of Charles Fort, the 17th-century star fort overlooking Kinsale harbour in County Cork" },
  { slug: "skibbereen-baltimore", match: ["Skibbereen", "Baltimore"], routing_keys: ["P81"], name: "Skibbereen & Baltimore", query: "Skibbereen, Cork", radius_km: 12, description: "a market town and neighbouring harbour village in West Cork", county: "cork",
    info: "Skibbereen and Baltimore are neighbouring settlements in West Cork, about 10km apart along the River Ilen and its estuary. Skibbereen is the region's principal market town, with a population of 2,778 recorded in Census 2022, and is closely associated with the Great Famine, a history documented at the Skibbereen Heritage Centre. Baltimore is a small harbour village at the tip of the peninsula — a sailing, angling, and diving centre and the ferry gateway to Sherkin Island, Cape Clear, and the islands of Roaringwater Bay. It is overlooked by the Baltimore Beacon, a white-painted navigational tower on the headland known locally as 'Lot's Wife'.",
    image: "/images/baltimore-harbour-beacon.jpg", imageAlt: "Fishing boats moored in Baltimore harbour, West Cork, with the white Baltimore Beacon ('Lot's Wife') on the headland beyond" },
  { slug: "limerick-city", match: ["Limerick"], routing_keys: ["V94"], name: "Limerick City", query: "Limerick City", radius_km: 3, description: "a vibrant city on the River Shannon", county: "limerick",
    info: "Limerick is a city on the River Shannon in County Limerick, with its historic core on King's Island where the river meets the Abbey River. Census 2022 recorded an urban population of 102,287, the third-largest in the Republic of Ireland. Landmarks include King John's Castle (1210), St Mary's Cathedral (1168), the Hunt Museum, and the Treaty Stone, linked to the 1691 Treaty of Limerick, on Clancy Strand." },
  { slug: "waterford-city", match: ["Waterford"], routing_keys: ["X91"], name: "Waterford City", query: "Waterford City", radius_km: 3, description: "Ireland's oldest city on the River Suir", county: "waterford",
    info: "Waterford is a city on the River Suir in County Waterford, founded by Vikings in 914 AD and considered Ireland's oldest city. Census 2022 recorded a population of 60,079, the fifth-largest in the state. Reginald's Tower, a 13th-14th century structure retaining its Norse name, is the oldest urban civic building in Ireland and now houses a museum. The city is historically associated with Waterford Crystal, produced there since 1783." },
  { slug: "kilkenny-city", match: ["Kilkenny"], routing_keys: ["R95"], name: "Kilkenny City", query: "Kilkenny", radius_km: 2, description: "the medieval capital of Ireland", county: "kilkenny",
    info: "Kilkenny is a city on the River Nore in County Kilkenny, set in a sheltered valley in Ireland's south-east. Census 2022 recorded a population of 27,184. Its medieval core, known as the Medieval Mile, includes surviving city walls and gates such as Talbot Tower. Kilkenny Castle, begun in 1204, overlooks the river, while St Canice's Cathedral stands beside a 9th-century round tower on the city's original monastic site." },
  { slug: "drogheda", match: ["Drogheda"], routing_keys: ["A92"], name: "Drogheda", query: "Drogheda, Louth", radius_km: 2, description: "a major town on the River Boyne in County Louth", county: "louth",
    info: "Drogheda is a port town on the River Boyne in County Louth, about 43 km north of Dublin, with a population of 44,135 at the 2022 Census. It occupies the river's lowest crossing point before the Boyne meets the Irish Sea. Medieval remains include St Laurence's Gate and Millmount, a Norman motte housing a museum; the Highlanes Gallery occupies a former Franciscan church, and Newgrange lies about 8 km west." },
  { slug: "dundalk", match: ["Dundalk"], routing_keys: ["A91"], name: "Dundalk", query: "Dundalk, Louth", radius_km: 2, description: "the largest town in County Louth", county: "louth",
    info: "Dundalk is the largest town in County Louth, midway between Dublin and Belfast and close to the border with Northern Ireland. Its 2022 Census population was 43,112 in the urban area, or 64,287 across the wider municipal district. The town developed from a Norman stronghold into a 19th-century manufacturing centre. Landmarks include the County Museum in a former distillery, Castle Roche, Oriel Park, and the nearby Proleek Dolmen." },
  { slug: "navan", match: ["Navan"], routing_keys: ["C15"], name: "Navan", query: "Navan, Meath", radius_km: 2, description: "the county town of Meath", county: "meath",
    info: "Navan is the county town of Meath, situated at the confluence of the Rivers Boyne and Blackwater about 50 km northwest of Dublin. Its population at the 2022 Census was 33,886. The town's layout dates to Norman times, though most surviving buildings are Victorian or Edwardian. Landmarks include Athlumney Castle, St Mary's Church, Navan Town Hall, and Pairc Tailteann, home ground of Meath's Gaelic football and hurling teams." },
  { slug: "naas", match: ["Naas"], routing_keys: ["W91"], name: "Naas", query: "Naas, Kildare", radius_km: 2, description: "the county town of Kildare", county: "kildare",
    info: "Naas is the county town of Kildare, in Leinster, with a population of 26,180 at the 2022 Census, making it the fourteenth-largest urban centre in Ireland. Originally a medieval walled market town, it now serves as a centre for local administration and commerce. Sites of interest include Naas Racecourse, Naas Town Hall (built in 1796 as a gaol), St David's Church, and the Grand Canal, which runs through the town." },
  { slug: "bray", match: ["Bray"], routing_keys: ["A98"], name: "Bray", query: "Bray, Wicklow", radius_km: 2, description: "a seaside town at the foot of the Wicklow Mountains", county: "wicklow",
    info: "Bray is a coastal town in County Wicklow, about 20 km south of Dublin at the foot of the Wicklow Mountains, with a population of 33,512 at the 2022 Census. Developed as a seaside resort after the railway arrived in 1854, it has a long promenade fronting a beach of sand and shingle. Landmarks include Bray Head, a 241-metre headland with walking trails, Killruddery House, and Ardmore Studios." },
  { slug: "swords", match: ["Swords"], routing_keys: ["K67", "K36"], name: "Swords", query: "Swords, Dublin", radius_km: 2, description: "the county town of Fingal in north County Dublin", county: "dublin",
    info: "Swords is a large town and the county town of Fingal in north County Dublin, about 13 km north of the city centre and close to Dublin Airport. One of the fastest-growing towns in Ireland, it recorded a population of over 40,000 at the 2022 Census. Landmarks include the medieval Swords Castle, a restored 12th-century archbishop's palace, a well-preserved round tower beside the old St Colmcille's church, and the Ward River Valley Park." },
  { slug: "lucan", match: ["Lucan"], routing_keys: ["K78"], name: "Lucan", query: "Lucan, Dublin", radius_km: 2, description: "a large commuter suburb on the Liffey in west Dublin", county: "dublin",
    info: "Lucan is a suburban town on the River Liffey in South Dublin, about 12 km west of the city centre, which grew rapidly from a village into a large commuter suburb in the late 20th century. Its population exceeded 46,000 at the 2022 Census. Landmarks include the Palladian Lucan House and its demesne, and the 18th-century spa that once made Lucan a fashionable resort." },
  { slug: "tallaght", match: ["Tallaght"], routing_keys: ["D24"], name: "Tallaght", query: "Tallaght, Dublin", radius_km: 2.5, description: "the largest town in South Dublin", county: "dublin",
    info: "Tallaght is the largest town in South Dublin and one of the most populous urban centres in Ireland, at the foot of the Dublin Mountains about 12 km southwest of the city centre. Its population exceeded 80,000 at the 2022 Census. It is home to Tallaght Stadium, The Square shopping centre, a Technological University Dublin campus and Tallaght University Hospital, and traces its origins to an 8th-century monastic settlement founded by St Maelruain." },
  { slug: "balbriggan", match: ["Balbriggan"], routing_keys: ["K32"], name: "Balbriggan", query: "Balbriggan, Dublin", radius_km: 2, description: "a coastal commuter town in north County Dublin", county: "dublin",
    info: "Balbriggan is a coastal town in Fingal, north County Dublin, about 30 km north of the city, known historically for its hosiery and textile industry. One of the youngest towns in Ireland by average age, it recorded a population of over 24,000 at the 2022 Census. Landmarks include the 19th-century Balbriggan lighthouse and harbour and a long sandy beach on the Irish Sea." },
  { slug: "sandyford", match: ["Sandyford"], routing_keys: ["D18", "D16"], name: "Sandyford", query: "Sandyford, Dublin", radius_km: 1.5, description: "a business-district suburb in south County Dublin", county: "dublin",
    info: "Sandyford is a suburb in Dún Laoghaire-Rathdown, south County Dublin, at the foot of Three Rock Mountain, incorporating the Sandyford Business District, one of the country's largest office and commercial parks. The area is served by the Luas Green Line and has seen substantial higher-density apartment development in recent decades. Nearby are Leopardstown Racecourse and the Ticknock forest trails." },
  { slug: "drumcondra", match: ["Drumcondra"], routing_keys: ["D09", "D03"], name: "Drumcondra", query: "Drumcondra, Dublin", radius_km: 1.5, description: "an established residential suburb on Dublin's northside", county: "dublin",
    info: "Drumcondra is an established residential suburb on Dublin's northside, about 3 km from the city centre along the River Tolka, in postal districts Dublin 9 and Dublin 3. It is home to Croke Park, Ireland's largest stadium and the headquarters of the GAA, the DCU St Patrick's campus, and Archbishop's House. The area is characterised by red-brick Victorian and Edwardian housing." },
  { slug: "terenure", match: ["Terenure"], routing_keys: ["D6W", "D06", "D12"], name: "Terenure", query: "Terenure, Dublin", radius_km: 1.5, description: "a leafy residential suburb on Dublin's southside", county: "dublin",
    info: "Terenure is a residential suburb on Dublin's southside, straddling postal districts Dublin 6W and Dublin 12 about 5 km from the city centre. It centres on a village crossroads and is bordered by Bushy Park, which runs along the River Dodder. The area is known for its solid Victorian and early 20th-century housing and for Terenure College, a secondary school founded in 1860." },
  { slug: "skerries", match: ["Skerries"], routing_keys: ["K34", "K56"], name: "Skerries", query: "Skerries, Dublin", radius_km: 1.5, description: "a coastal town and former fishing village north of Dublin", county: "dublin",
    info: "Skerries is a coastal town in Fingal, north County Dublin, about 30 km from the city, long popular as a seaside resort and now a commuter town with a population of around 10,000. Its harbour supports a small fishing fleet, and landmarks include the restored Skerries Mills — two windmills and a watermill — and the offshore islands that give the town its name, from the Norse for 'rocks'." },
  { slug: "blanchardstown", match: ["Blanchardstown"], routing_keys: ["D15"], name: "Blanchardstown", query: "Blanchardstown, Dublin", radius_km: 2.5, description: "a large suburban town in west County Dublin", county: "dublin",
    info: "Blanchardstown is a large suburban town in Fingal, west County Dublin, about 10 km from the city centre, which expanded rapidly from a village during the late 20th century. It is home to the Blanchardstown Centre, one of Ireland's largest shopping centres, Connolly Hospital, and a Technological University Dublin campus. Nearby are the National Aquatic Centre and Tolka Valley Park." },
  { slug: "newbridge", match: ["Newbridge"], routing_keys: ["W12"], name: "Newbridge", query: "Newbridge, Kildare", radius_km: 2, description: "the largest town in County Kildare", county: "kildare",
    info: "Newbridge (Droichead Nua) is the largest town in County Kildare, on the River Liffey about 50 km southwest of Dublin, with a population of over 24,000 at the 2022 Census. It grew around a 19th-century cavalry barracks and is known today for Newbridge Silverware and its Museum of Style Icons, the Whitewater Shopping Centre, and its proximity to the Curragh plains and racecourse." },
  { slug: "maynooth", match: ["Maynooth"], routing_keys: ["W23"], name: "Maynooth", query: "Maynooth, Kildare", radius_km: 2, description: "a university town in north County Kildare", county: "kildare",
    info: "Maynooth is a university town in north County Kildare, about 25 km west of Dublin, home to Maynooth University and St Patrick's College, Ireland's national seminary, founded in 1795. Landmarks include the ruined Maynooth Castle, a 12th-century Fitzgerald stronghold, and the Royal Canal, which runs through the town. Its resident population was recorded at over 17,000 at the 2022 Census." },
  { slug: "celbridge", match: ["Celbridge"], routing_keys: ["W23"], name: "Celbridge", query: "Celbridge, Kildare", radius_km: 2, description: "a Liffeyside commuter town in north County Kildare", county: "kildare",
    info: "Celbridge is a town on the River Liffey in north County Kildare, about 23 km west of Dublin, with a population of around 21,000 at the 2022 Census. It is home to Castletown House, the largest and one of the earliest Palladian country houses in Ireland, built from 1722 for William Conolly, Speaker of the Irish House of Commons. The town developed as a Dublin commuter base in recent decades." },
  { slug: "leixlip", match: ["Leixlip"], routing_keys: ["W23"], name: "Leixlip", query: "Leixlip, Kildare", radius_km: 1.5, description: "a riverside town on the Kildare–Dublin border", county: "kildare",
    info: "Leixlip is a town on the River Liffey at the border of counties Kildare and Dublin, about 17 km west of Dublin, whose name derives from the Norse for 'salmon leap'. A major employment centre, it is home to large Intel and Hewlett-Packard manufacturing campuses. Landmarks include Leixlip Castle and the Wonderful Barn, an 18th-century conical grain store." },
  { slug: "greystones", match: ["Greystones"], routing_keys: ["A63"], name: "Greystones", query: "Greystones, Wicklow", radius_km: 1.5, description: "a coastal commuter town in County Wicklow", county: "wicklow",
    info: "Greystones is a coastal town in County Wicklow, about 27 km south of Dublin, which grew from a fishing village into a commuter town and won an international 'most liveable community' award in 2008. Census 2022 recorded a population of around 18,000. It has a redeveloped harbour and marina, a shingle-and-sand beach, and the cliff walk to Bray around Bray Head." },
  { slug: "ashbourne", match: ["Ashbourne"], routing_keys: ["A84"], name: "Ashbourne", query: "Ashbourne, Meath", radius_km: 2, description: "a fast-growing commuter town in south County Meath", county: "meath",
    info: "Ashbourne is a commuter town in south County Meath, about 20 km north of Dublin and one of the fastest-growing towns in Ireland during the 2000s, with a population of around 13,000 at the 2022 Census. Largely a modern town, it developed along the old Dublin–Derry coach road. The 1916 Battle of Ashbourne, a rare rebel success during the Easter Rising, was fought nearby." },
  { slug: "portlaoise", match: ["Portlaoise"], routing_keys: ["R32"], name: "Portlaoise", query: "Portlaoise, Laois", radius_km: 2, description: "the county town of Laois in the Irish midlands", county: "laois",
    info: "Portlaoise is the county town of Laois, in the Irish midlands about 80 km southwest of Dublin, and one of the fastest-growing towns in the country, with a population of over 22,000 at the 2022 Census. A key hub on the M7 motorway and Dublin–Cork railway, it is known for Portlaoise and Midlands prisons and for the restored Fort Protector, an early plantation-era fortification." },
  { slug: "mullingar", match: ["Mullingar"], routing_keys: ["N91"], name: "Mullingar", query: "Mullingar, Westmeath", radius_km: 2, description: "the county town of Westmeath", county: "westmeath",
    info: "Mullingar is the county town of Westmeath, in the Irish midlands about 80 km northwest of Dublin, set amid a lake-studded landscape that includes Loughs Owel and Ennell. Census 2022 recorded a population of over 22,000. The Royal Canal passes through the town, and its landmarks include the twin-spired Cathedral of Christ the King, completed in 1936." },
  { slug: "athlone", match: ["Athlone"], routing_keys: ["N37"], name: "Athlone", query: "Athlone, Westmeath", radius_km: 2, description: "a Shannonside town at the centre of Ireland", county: "westmeath",
    info: "Athlone is a town on the River Shannon near the geographic centre of Ireland, straddling the Westmeath–Roscommon border about 120 km west of Dublin, with a population of over 22,000 at the 2022 Census. It is dominated by the 13th-century Athlone Castle guarding the river crossing, and is home to Sean's Bar, which claims to be Ireland's oldest pub. The Technological University of the Shannon has a major campus in the town." },
  { slug: "gorey", match: ["Gorey"], routing_keys: ["Y25"], name: "Gorey", query: "Gorey, Wexford", radius_km: 2, description: "a market and commuter town in north County Wexford", county: "wexford",
    info: "Gorey is a market town in north County Wexford, about 90 km south of Dublin, one of the fastest-growing towns in the region as a commuter and coastal base, with a population of around 11,000 at the 2022 Census. Laid out as a planned town in the early 17th century, it has a broad Main Street and lies close to the beaches of Courtown. The rebel camp on Gorey Hill features in the history of the 1798 Rebellion." },
  { slug: "ennis", match: ["Ennis"], routing_keys: ["V95"], name: "Ennis", query: "Ennis, Clare", radius_km: 2, description: "the county town of Clare", county: "clare",
    info: "Ennis is the county town of Clare, on the River Fergus in the west of Ireland, with a population of around 27,000 at the 2022 Census, the largest town in the county. Known for its narrow medieval street pattern, it grew around Ennis Friary, a Franciscan house founded in the 13th century. The town is a noted centre of traditional Irish music and was designated Ireland's first 'Information Age Town' in 1997." },
  { slug: "tralee", match: ["Tralee"], routing_keys: ["V92"], name: "Tralee", query: "Tralee, Kerry", radius_km: 2, description: "the county town of Kerry", county: "kerry",
    info: "Tralee is the county town of Kerry, in the southwest of Ireland at the base of the Dingle Peninsula, with a population of around 26,000 at the 2022 Census, the largest town in the county. It is best known for the annual Rose of Tralee international festival. Landmarks include the Kerry County Museum, the restored Blennerville Windmill, and the Tralee Ship Canal." },
  { slug: "letterkenny", match: ["Letterkenny"], routing_keys: ["F92"], name: "Letterkenny", query: "Letterkenny, Donegal", radius_km: 2, description: "the largest town in County Donegal", county: "donegal",
    info: "Letterkenny is the largest town in County Donegal, in the northwest of Ireland on the River Swilly, with a population of around 22,000 at the 2022 Census, and the commercial and administrative hub of the county. Known as the 'Cathedral Town' for St Eunan's Cathedral, completed in 1901, it is home to an Atlantic Technological University campus and one of the longest main streets in Ireland." },
  { slug: "mallow", match: ["Mallow"], routing_keys: ["P51"], name: "Mallow", query: "Mallow, Cork", radius_km: 2, description: "a Blackwater market town in north County Cork", county: "cork",
    info: "Mallow is a town on the River Blackwater in north County Cork, about 35 km north of Cork city, historically a fashionable spa resort known as the 'Irish Bath', with a population of around 13,000 at the 2022 Census. A key rail junction and market centre, its landmarks include the ruined Mallow Castle, the neighbouring 19th-century mansion, and the half-timbered Clock House on the main street." },
  { slug: "killarney", match: ["Killarney"], routing_keys: ["V93"], name: "Killarney", query: "Killarney, Kerry", radius_km: 2, description: "a lakeland tourist town in County Kerry", county: "kerry",
    info: "Killarney is a town in County Kerry, in the southwest of Ireland and one of the country's foremost tourist destinations, set beside the lakes and mountains of Killarney National Park, with a population of around 14,000 at the 2022 Census. The park, Ireland's first, established in 1932, contains Muckross House, Ross Castle, Torc Waterfall and Ladies View, and the town is the gateway to the Ring of Kerry." },
  { slug: "castlebar", match: ["Castlebar"], routing_keys: ["F23"], name: "Castlebar", query: "Castlebar, Mayo", radius_km: 2, description: "the county town of Mayo", county: "mayo",
    info: "Castlebar is the county town of Mayo, in the west of Ireland, with a population of around 13,000 at the 2022 Census, the largest town in the county. It was the site of the 1798 'Races of Castlebar', when a Franco-Irish force routed British troops. Landmarks include the tree-lined Mall and the National Museum of Ireland – Country Life at nearby Turlough Park, and the Land League was founded in the town in 1879." },
  { slug: "clonmel", match: ["Clonmel"], routing_keys: ["E91"], name: "Clonmel", query: "Clonmel, Tipperary", radius_km: 2, description: "the largest town in County Tipperary", county: "tipperary",
    info: "Clonmel is the largest town in County Tipperary, on the River Suir in the south of the county, with a population of around 18,000 at the 2022 Census; its name means 'meadow of honey'. Historically a walled town, surviving features include the West Gate and sections of the medieval walls. It was the birthplace of the Bianconi transport network in 1815 and of the novelist Laurence Sterne." },
  { slug: "nenagh", match: ["Nenagh"], routing_keys: ["E45"], name: "Nenagh", query: "Nenagh, Tipperary", radius_km: 2, description: "a market town in north County Tipperary", county: "tipperary",
    info: "Nenagh is a market town in north County Tipperary, about 33 km northeast of Limerick, with a population of around 10,000 at the 2022 Census. It is dominated by Nenagh Castle, a well-preserved circular keep built around 1200 by the Butler family and one of the finest of its kind in Ireland. Other landmarks include the former county gaol and governor's house, now the Nenagh Heritage Centre." },
  { slug: "dungarvan", match: ["Dungarvan"], routing_keys: ["X35"], name: "Dungarvan", query: "Dungarvan, Waterford", radius_km: 2, description: "a harbour town on the County Waterford coast", county: "waterford",
    info: "Dungarvan is a harbour town and the administrative centre of County Waterford, on the south coast where the Colligan River meets Dungarvan Bay, with a population of around 10,000 at the 2022 Census. It is overlooked by the remains of King John's Castle, a Norman fortification by the harbour, and is the western terminus of the Waterford Greenway, a 46 km walking and cycling route along a former railway line." },
  { slug: "sligo", match: ["Sligo"], routing_keys: ["F91"], name: "Sligo", query: "Sligo, County Sligo", radius_km: 2, description: "the principal town of Ireland's northwest", county: "sligo",
    info: "Sligo is the county town of Sligo, in the northwest of Ireland where the Garavogue River runs between Lough Gill and the Atlantic, with a population of around 20,000 at the 2022 Census, the largest urban centre in the northwest. It is strongly associated with the poet W. B. Yeats, buried at nearby Drumcliffe beneath Benbulben mountain. Landmarks include the 13th-century Sligo Abbey and The Model arts centre." },
  { slug: "carlow", match: ["Carlow"], routing_keys: ["R93"], name: "Carlow", query: "Carlow, County Carlow", radius_km: 2, description: "the county town of Carlow", county: "carlow",
    info: "Carlow is the county town of Carlow, on the River Barrow in the southeast midlands about 80 km from Dublin, with a population of around 25,000 at the 2022 Census. Landmarks include the remains of Carlow Castle, a 13th-century Norman fortress; the Brownshill Dolmen, whose capstone is reputedly the heaviest in Europe; and the Cathedral of the Assumption, completed in 1833. The town is home to the South East Technological University." },
];

export const COUNTIES = [
  "Carlow","Cavan","Clare","Cork","Donegal","Dublin","Galway",
  "Kerry","Kildare","Kilkenny","Laois","Leitrim","Limerick","Longford",
  "Louth","Mayo","Meath","Monaghan","Offaly","Roscommon","Sligo",
  "Tipperary","Waterford","Westmeath","Wexford","Wicklow",
];

export function countySlug(county: string): string {
  return county.toLowerCase().replace(/\s+/g, "-");
}

export function countyFromSlug(slug: string): string | undefined {
  return COUNTIES.find(c => countySlug(c) === slug);
}

export function areaFromSlug(slug: string): AreaConfig | undefined {
  return AREAS.find(a => a.slug === slug);
}

// Dublin eircode routing keys with friendly names
export const DUBLIN_EIRCODE_AREAS: Record<string, string> = {
  D01: "Dublin 1", D02: "Dublin 2", D03: "Dublin 3", D04: "Dublin 4",
  D05: "Dublin 5", D06: "Dublin 6", D6W: "Dublin 6W", D07: "Dublin 7",
  D08: "Dublin 8", D09: "Dublin 9", D10: "Dublin 10", D11: "Dublin 11",
  D12: "Dublin 12", D13: "Dublin 13", D14: "Dublin 14", D15: "Dublin 15",
  D16: "Dublin 16", D17: "Dublin 17", D18: "Dublin 18", D20: "Dublin 20",
  D22: "Dublin 22", D24: "Dublin 24",
};

// Provinces of the Republic of Ireland → county slugs (display order).
// Covers all 26 counties in COUNTIES.
export const PROVINCES: { name: string; counties: string[] }[] = [
  { name: "Leinster", counties: ["carlow", "dublin", "kildare", "kilkenny", "laois", "longford", "louth", "meath", "offaly", "westmeath", "wexford", "wicklow"] },
  { name: "Munster",  counties: ["clare", "cork", "kerry", "limerick", "tipperary", "waterford"] },
  { name: "Connacht", counties: ["galway", "leitrim", "mayo", "roscommon", "sligo"] },
  { name: "Ulster",   counties: ["cavan", "donegal", "monaghan"] },
];

// All AREAS whose parent county matches the given county slug.
export function areasForCounty(countySlug: string): AreaConfig[] {
  return AREAS.filter(a => a.county === countySlug);
}

// The province name a county slug belongs to (undefined if unknown).
export function provinceForCounty(countySlug: string): string | undefined {
  return PROVINCES.find(p => p.counties.includes(countySlug))?.name;
}

// The parent county slug for an area slug (undefined if unknown).
export function countyForArea(areaSlug: string): string | undefined {
  return AREAS.find(a => a.slug === areaSlug)?.county;
}
